# You can define the number of kits that a player can save here. By default, players will have permissions for all the kits,
# but you can use a Permission Manager, such as LuckPerms, to set, for example, 'kitsx.kit7' to false for a player or a LuckPerms group,
# and, They won't be able to load/use the Kit 7

kits: 7

broadcast:
  kit-load: true
  kit-load-message: "&#7cff6e%player% loaded %kit%."
  kitroom-open: true
  kitroom-open-message: "&#7cff6e%player% opened the Virtual Kit Room."
  premadekit-load: true
  premadekit-load-message: "&#7cff6e%player% loaded the premade kit."

messages:
  no-permission: "&#ffa6a6You do not have permission to use this command."
  blacklisted-region: "&#ffa6a6You cannot use this command here."
  kit-saved: "&#7cff6e%kit% saved successfully!"
  kit-loaded: "&#7cff6e%kit% loaded successfully!"
  enderchest-saved: "&#7cff6eEnder chest for %kit% saved successfully!"
  premade-kit-saved: "&#7cff6ePremade kit saved successfully!"
  premade-kit-loaded: "&#7cff6ePremade kit loaded successfully!"
  premade-kit-empty: "&#ffa6a6The premade kit is empty."
  auto-rekit-kit-selected: "&#7cff6eAuto Rekit kit set to %kit%."
  send-auto-rekit-message: true
  auto-rekit-message: "&#7cff6eAutomatically rekitted for you. Use /autorekit to toggle or edit the kit."

blacklisted-regions:
  - "arena1"
  - "arena2"